<?php $arrTopCatCollection = Mage::getModel('catalog/category')->getCollection()
                                ->addFieldToFilter('is_active', array('eq'=>'1'))
                                ->addAttributeToSort('position', 'asc')
                                 ->addAttributeToFilter('level', 2);
$strDefaultImageUrl = Mage::getBaseUrl('media').'catalog/category/placeholder.jpg';
// $strDefaultImageUrl = $this->getSkinUrl('images/category_placeholder.jpg');
?>
<?php if(count($arrTopCatCollection) > 0){ ?>
    <div class="home_categories clearer">
        <div class="home_categories-inner">     
            <ul>
                <?php foreach ($arrTopCatCollection as $objCategory) { ?>
                    <?php $objCategory = Mage::getModel('catalog/category')->load($objCategory->getId());?>
                    <?php if($objCategory->getThumbnail()){
                        $strCatImageUrl = Mage::getBaseUrl('media').'catalog/category/' . $objCategory->getThumbnail();
                    }else{
                        $strCatImageUrl = $strDefaultImageUrl;
                    }?>
                    <li class="cat-item grid12-3">
                        <a href="<?php echo $objCategory->getUrl(); ?>">
                            <img alt="<?php echo $this->escapeHtml($objCategory->getName()); ?>" title="<?php echo $this->escapeHtml($objCategory->getName()); ?>" src="<?php echo $strCatImageUrl; ?>">                   
                            <span class="category_title"><?php echo $this->escapeHtml($objCategory->getName()); ?></span>
                            <span class="shop-btn"><?php echo $this->__('Shop Now'); ?></span>

                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
    <style type="text/css">
        .home_categories-inner {
  display: block;
  float: left;
  margin: 30px 0;
  width: 100%;
}
.category_title {
  display: block;
  font-size: 20px;
  margin: 14px 0;
  text-align: center;
}
.cat-item {
  text-align: center;
}
.shop-btn {
  background: #d91f1f none repeat scroll 0 0;
  color: #fff;
  display: inline-block;
  font-size: 16px;
  margin-top: 10px;
  padding: 10px 30px;
  text-transform: uppercase;
}
    </style>
<?php } ?>
